stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY shop@vds.msaserj.ru "
      systemctl --user stop shopsrv.service &&
      rm -fr ~/shopsrv/srv &&
      git clone https://gitlab.com/msaserj/glider-shop-back.git ~/shopsrv/srv &&
      cd ~/shopsrv/srv &&
      npm install &&
      systemctl --user start shopsrv.service "
