stages:
  - stop and delete old srv
  - git clone
  - install and start

delete-old-srv:
  stage: stop and delete old srv
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@vds.msaserj.ru "
      systemctl stop shop.service &&
      rm -fr /home/shop/shopsrv/srv &&
      exit"

git-clone:
  stage: git clone
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@vds.msaserj.ru "
      git clone https://gitlab.com/msaserj/glider-shop-back.git /home/shop/shopsrv/srv &&
      exit"

install-start:
  stage: install and start
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@vds.msaserj.ru "
      cd /home/shop/shopsrv/srv &&
      yarn install &&
      systemctl start shop.service "
